Repository TommasU/scrivener, pull requests merged in 2021-11, with the labels that each got.

#27 Code documentation review and edits
  source/main/transcribe.py
  source/main/transcribe_yt.py
  source/scrivener_user_interface.py
Labels: documentation, Code Quality

#29 Rt sentiment
  requirements.txt
  source/scrivener_user_interface.py
Labels: enhancement

#31 Basic testing
  .github/workflows/main.yml
  requirements.txt
  setup.py
  source/__init__.py
  source/main/punctuation.py
  source/main/transcribe.py
  source/main/transcribe_yt.py
  test/__init__.py
  test/conftest.py
  test/test_punctuation.py
  test/test_transcribe_yt.py
Labels: Testing

#38 Added autopep8 to workflow
  .github/workflows/autopep8.yml
Labels: Code Quality

#37 Jv formatter
  docs/Project Documentation.pdf
  docs/proj1rubric.md
  docs/proj1rubricComments.pdf
  docs/proj2rubric.md
Labels: documentation

#41 Ver imp rt
  README.md
  docs/Project2Changes.md
Labels: documentation, Code Quality
